//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReshimgathiMatrimony
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginEvent
    {
        public System.Guid Id { get; set; }
        public string LoginId { get; set; }
        public string LastLoginDate { get; set; }
        public Nullable<bool> FailedAttempts { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
