//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReshimgathiMatrimony
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationPhase1
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> LoginId { get; set; }
        public string ReshimgathiId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsPhoneVerified { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
