//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReshimgathiMatrimony
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReshimgathiMatrimonyEntities : DbContext
    {
        public ReshimgathiMatrimonyEntities()
            : base("name=ReshimgathiMatrimonyEntities")
        {
            //Disable initializer
            Database.SetInitializer<ReshimgathiMatrimonyEntities>(null);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppConstant> AppConstants { get; set; }
        public virtual DbSet<LoginEvent> LoginEvents { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<RegistrationPhase1> RegistrationPhase1 { get; set; }
    }
}
